### PR TITLE
add Github Actions test

### PR DESCRIPTION
**Pull request by wonda-tea-coffee**
- Add test for GithubActions
  - https://github.com/88labs/carrierwave_backgrounder/pull/2/commits/8b16f3b08366a878e0deddb76d963aa74ef17261
  - https://github.com/88labs/carrierwave_backgrounder/pull/2/commits/93e950d794196ff9e4c2e3e148b1785565528d60
- Fixed so that all tests pass
  - https://github.com/88labs/carrierwave_backgrounder/pull/2/commits/8d295423748a40a23aca2a5f622662a74e7b08ff
  - https://github.com/88labs/carrierwave_backgrounder/pull/2/commits/3e1eb3559fb06291b2dbb2c78832715b4a45a70e
  - https://github.com/88labs/carrierwave_backgrounder/pull/2/commits/455ecf2a94e93010cb7172ecbdeb81afc7802789

### CODE REVIEW

**Comment by tricknotes** [comment]
Totally good 👍 

BTW, 455ecf2a94e93010cb7172ecbdeb81afc7802789 is needed?
It seems just syntax change.

**Review by onodera0314 — APPROVED** [review]
shingo4

**Comment by wonda-tea-coffee** [comment]
@tricknotes 
Thank you 🎉 

This was necessary because the test failed with the following error.

```
  4) CarrierWave::Workers::StoreAsset#perform removes tmp directory on success
     Failure/Error: FileUtils.rm_r(tmp_directory, :force => true)

       FileUtils received :rm_r with unexpected arguments
         expected: ("/home/runner/work/carrierwave_backgrounder/carrierwave_backgrounder/spec/backgrounder/workers/fixtures/images", {:force=>true})
              got: ("/home/runner/work/carrierwave_backgrounder/carrierwave_backgrounder/spec/backgrounder/workers/fixtures/images", {:force=>true})
     # ./lib/backgrounder/workers/store_asset_mixin.rb:26:in `perform'
     # ./spec/backgrounder/workers/store_asset_spec.rb:37:in `block (3 levels) in <top (required)>'
```

**Comment by tricknotes** [comment]
Thanks, I see :+1:

I think using keyword arguments is better approach, instead of using hash.
e.g.
``` diff
diff --git a/spec/backgrounder/workers/store_asset_spec.rb b/spec/backgrounder/workers/store_asset_spec.rb
index 5e3fc75..659017c 100644
--- a/spec/backgrounder/workers/store_asset_spec.rb
+++ b/spec/backgrounder/workers/store_asset_spec.rb
@@ -32,7 +32,7 @@ RSpec.describe CarrierWave::Workers::StoreAsset do
     end
 
     it 'removes tmp directory on success' do
-      expect(FileUtils).to receive(:rm_r).with(fixtures_path, { force: true }).once
+      expect(FileUtils).to receive(:rm_r).with(fixtures_path, force: true).once
       expect(user).to receive(:save!).once.and_return(true)
       worker.perform
     end
```

However, there are no warning on CI by this approach.
I'm agree with this change :+1:

**Review by tricknotes — APPROVED** [review]

**Comment by wonda-tea-coffee** [comment]
I certainly agree.

> I think using keyword arguments is better approach, instead of using hash.

However, having fixed it this way, I didn't immediately know how to fix a failing test... 😕 

I'm going to merge them in this state this time 🙏

**Pull request merged**
